### PR TITLE
More pages

### PR DESCRIPTION
**Pull request by cfarm**
- todo: add code of conduct

splits workshops + projects sign ups into sep pages

### CODE REVIEW

**Comment by ascott1** [comment]
Looks good to me. :+1: 

 Are the new pages linked in the sidebar nav?

**Comment by willbarton** [comment]
@ascott1 Looks like it from the `_config.yml`.

@cfarm You committed `_site`. Did you mean to do that?

**Comment by cfarm** [comment]
is it not sposed to be? we need to fix the .gitignore in that case

**Comment by willbarton** [comment]
thumbs_up_cat

**Comment by willbarton** [comment]
Opps. This was for master instead of gh-pages. I'll fix that, but in the mean time, is there any objection to deleting master altogether (once these changes get merged into gh-pages)?

**Pull request merged**
