### PR TITLE
add event description

### PR DESCRIPTION
**Pull request by cfarm**
for people who want to know what this is about.

copy for "what it is" mostly taken from http://cfpb.github.io intro paragraph.

as usual check it out at http://cfarm.github.io/hackathon

### CODE REVIEW

**Comment by willbarton** [comment]
There will be pizza?

**Comment by ascott1** [comment]
PIZZA?????

**Comment by cfarm** [comment]
of course. source for pizza rumor https://github.com/cfpb/hackathon/issues/1#issue-114342455

**Comment by willbarton** [comment]
So Dollar Bill (@virtix) will bring us pizza? Sounds good to me.

stock-illustration-57006526-pizza-with-thumbs-up

**Pull request merged**
